-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.servicios_salud
(
    id serial NOT NULL,
    nombre text COLLATE pg_catalog."default",
    tipo text COLLATE pg_catalog."default",
    capacidad integer,
    horario text COLLATE pg_catalog."default",
    telefono text COLLATE pg_catalog."default",
    estado text COLLATE pg_catalog."default",
    ubicacion geometry,
    direccion text COLLATE pg_catalog."default",
    CONSTRAINT servicios_salud_pkey PRIMARY KEY (id)
);

COMMENT ON TABLE public.servicios_salud
    IS 'Contiene los puntos de servicios de salud: hospitales, farmacias y cl¡nicas m¢viles.';

COMMENT ON COLUMN public.servicios_salud.id
    IS 'Clave primaria secuencial.';

COMMENT ON COLUMN public.servicios_salud.nombre
    IS 'Nombre del establecimiento de salud.';

COMMENT ON COLUMN public.servicios_salud.tipo
    IS 'Tipo de servicio: hospital, cl¡nica m¢vil o farmacia.';

COMMENT ON COLUMN public.servicios_salud.capacidad
    IS 'N£mero m ximo de camas o atenci¢n simult nea.';

COMMENT ON COLUMN public.servicios_salud.horario
    IS 'Horario de atenci¢n, e.g. 24h o 8h-18h.';

COMMENT ON COLUMN public.servicios_salud.telefono
    IS 'Tel‚fono de contacto.';

COMMENT ON COLUMN public.servicios_salud.estado
    IS 'Estado operativo o activo.';

COMMENT ON COLUMN public.servicios_salud.ubicacion
    IS 'Geometr¡a de tipo Point (SRID 4326).';

COMMENT ON COLUMN public.servicios_salud.direccion
    IS 'Direcci¢n f¡sica completa.';

CREATE TABLE IF NOT EXISTS public.zonas
(
    id serial NOT NULL,
    nombre text COLLATE pg_catalog."default",
    tipo text COLLATE pg_catalog."default",
    descripcion text COLLATE pg_catalog."default",
    geom geometry,
    CONSTRAINT zonas_pkey PRIMARY KEY (id)
);

COMMENT ON TABLE public.zonas
    IS 'Define  reas geogr ficas de riesgo o atenci¢n.';

COMMENT ON COLUMN public.zonas.id
    IS 'Clave primaria secuencial.';

COMMENT ON COLUMN public.zonas.nombre
    IS 'Nombre descriptivo de la zona.';

COMMENT ON COLUMN public.zonas.tipo
    IS 'Categor¡a: riesgo o atenci¢n.';

COMMENT ON COLUMN public.zonas.descripcion
    IS 'Detalles sobre la caracter¡stica de la zona.';

COMMENT ON COLUMN public.zonas.geom
    IS 'Geometr¡a de tipo Polygon (SRID 4326).';
END;